name: automated deploy to aws

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: build, push and deploy
    runs-on: self-hosted

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY_NAME: ${{ secrets.ECR_REPOSITORY_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ensure ECR repository exists and creates if not
        run: |
          aws ecr describe-repositories \
            --repository-names $ECR_REPOSITORY_NAME \
            --region $AWS_REGION || \
          aws ecr create-repository \
            --repository-name $ECR_REPOSITORY_NAME \
            --region $AWS_REGION

      - name: build and push docker image
        run: |
          IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:latest
          docker build --platform linux/amd64 -t $IMAGE_URI ./TestApp/
          docker push $IMAGE_URI

      - name: Install Node and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install CDK and project dependencies
        run: |
          npm install -g aws-cdk
          npm ci

      - name: check if CDK bootstrap is required
        id: check_bootstrap
        run: |
          if aws ssm get-parameter --name "/cdk-bootstrap/hnb659fds/version" > /dev/null 2>&1; then
            echo "Bootstrap already done."
            echo "bootstrap_required=false" >> $GITHUB_OUTPUT
          else
            echo "Bootstrap is required."
            echo "bootstrap_required=true" >> $GITHUB_OUTPUT
          fi

      - name: CDK Bootstrap (only if required)
        if: steps.check_bootstrap.outputs.bootstrap_required == 'true'
        run: |
          cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION

      - name: CDK Deploy
        run: |
          cdk deploy --require-approval never
